version: "3"
services:
  postgres:
    container_name: postgres-clickhotel
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: clickhotel
      POSTGRES_PASSWORD: jRQnOdqmKNhlrzoL
      POSTGRES_DB: clickhotel_api
      PGDATA: /var/lib/postgresql/data
    ports:
      - 15432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-clickhotel

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
    networks:
      - postgres-clickhotel      

  api:
    container_name: api-clickhotel
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: "./api"
    env_file:
      - ./api/.env
    restart: always
    ports:
      - 3001:3000
    volumes:
      - /app/node_modules
      - ./api:/app      
    networks:
      - postgres-clickhotel      

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./app
    volumes:
      - /app/node_modules
      - ./app:/app
    networks:
      - postgres-clickhotel       

  pgadmin:
    container_name: pgadmin-clickhotel
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "andre@clicksul.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2023!"
    ports:
      - 16542:80
    depends_on:
      - postgres
    networks:
      - postgres-clickhotel

networks:
  postgres-clickhotel:
    driver: bridge      