version: '3.8'
services:
  postgres:
    container_name: postgres-clickhotel
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=clickhotel
      - POSTGRES_PASSWORD=jRQnOdqmKNhlrzoL
      - POSTGRES_DB=clickhotel_api
    ports:
      - '15432:5432'
    volumes:
      - postgres-clickhotel-volume:/var/lib/postgresql/data
    networks:
      - postgres-clickhotel

  api:
    container_name: api-clickhotel
    depends_on:
      - postgres
    build: ./api
    env_file:
      - ./api/.env
    restart: always
    ports:
      - 3001:3000

  app:
    container_name: app-clickhotel
    depends_on:
      - postgres
    build: ./app
    env_file:
      - ./app/.env
    volumes:
      - app-clickhotel-volume:/var/www/html

  nginx:  
    container_name: nginx-clickhotel
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - app-clickhotel-volume:/var/www/html
    depends_on:
      - postgres
      - api
      - app

  pgadmin:
    container_name: pgadmin-clickhotel
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "andre@clicksul.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2023!"
    ports:
      - "16542:80"
    depends_on:
      - postgres
    networks:
      - postgres-clickhotel

networks:
  postgres-clickhotel:
    driver: bridge

volumes:
  postgres-clickhotel-volume:
  app-clickhotel-volume:
  