version: "4"
services:
  postgres:
    container_name: postgres-clickhotel
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: clickhotel
      POSTGRES_PASSWORD: jRQnOdqmKNhlrzoL
      POSTGRES_DB: clickhotel_api
      PGDATA: /var/lib/postgresql/data
    ports:
      - 15432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    container_name: api-clickhotel
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: ./api
    restart: always
    env_file:
      - ./api/.env
    ports:
      - 3001:3001
 
  client:
    container_name: client-clickhotel
    build:
      dockerfile: Dockerfile
      context: ./app
    env_file:
      - ./app/.env
    volumes:
      - client-volume:/var/www/html 

  pgadmin:
    container_name: pgadmin-clickhotel
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "andre@clicksul.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2023!"
    ports:
      - 16542:80
    depends_on:
      - postgres

  nginx:
    container_name: nginx-clickhotel
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - client-volume:/var/www/html
    depends_on:
      - postgres
      - api
      - client
    network_mode: host

volumes:
  postgres-data:
  client-volume: