version: "4"
services:
  postgres:
    container_name: postgres-clickhotel
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: clickhotel
      POSTGRES_PASSWORD: jRQnOdqmKNhlrzoL
      POSTGRES_DB: clickhotel_api
      PGDATA: /var/lib/postgresql/data
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin-clickhotel
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "andre@clicksul.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2023!"
    ports:
      - "16542:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin      

  api:
    container_name: api-clickhotel
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: ./api
    restart: always
    env_file:
      - ./api/.env
    ports:
      - "3000:3000"
 
  client:
    container_name: client-clickhotel
    build:
      dockerfile: Dockerfile
      context: ./app
    env_file:
      - ./app/.env
    depends_on:
      - api
    volumes:
      - client_volume:/var/www/html
      
  nginx:
    container_name: nginx-clickhotel
    image: nginx:alpine
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    restart: always
    ports:
      - 8080:80
    depends_on:
      - postgres
      - api
      - client

volumes:
  postgres_data:
  pgadmin_data:
  client_volume: