version: '3.8'
services:
  app:
    container_name: app-clickhotel
    build: ./
    env_file:
      - ./.env
    ports:
      - 5173:5173
    volumes:
      - app-clickhotel-volume:/var/www/html

  nginx:  
    container_name: nginx-clickhotel
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:80
    volumes:
      - app-clickhotel-volume:/var/www/html
    depends_on:
      - app

  